project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/p11/
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/p11/
  navbar:
    logo: IQB-klein.png
    search: true
    left:
        - href: index.qmd
          text: "Metadatenprofile für Testaufgaben: Mathematik Primar"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
