---
title: Metadatenprofile für Testaufgaben - Mathematik Primar
---

ID of profile-store: `map`

Publisher: IQB - Institut zur Qualitätsentwicklung im Bildungswesen

Maintainer: IQB - Institut zur Qualitätsentwicklung im Bildungswesen

2 Profile definiert:

# IQB Mathematik Primar - Aufgabe

ID of profile: `https://raw.githubusercontent.com/iqb-vocabs/p11/master/unit.json`

| Name/Label | Typ | Parameter | ID Profil-Eintrag |
| :--- | :---: | :--- | :---: |
| Entwickler:in | Text |Einzeilig, Sprache(n): de | iqb_author |
| Für SPF geeignet | Ja/Nein |Text für WAHR: ja, Text für FALSCH: nein | a1 |
| Kopfhörereinsatz | [Vokabular](https://w3id.org/iqb/v24/kh/) | url: 'https://w3id.org/iqb/v24/kh/', Einmalauswahl, Nummerierung unterdrückt | iqb_phones |
| Leitidee | [Vokabular](https://w3id.org/iqb/v10/i1/) | url: 'https://w3id.org/iqb/v10/i1/', Einmalauswahl, Zeige nur erste Ebene | w8 |
| Aufgabenzeit | Zahl |Kommastellen: 0, Mindestwert: 0, Maximalwert: kein, als Sekunden | iqb_time_unit |
| Stimuluszeit | Zahl |Kommastellen: 0, Mindestwert: 0, Maximalwert: kein, als Sekunden | iqb_time_stimulus |
| Quellenangaben | Text |Mehrzeilig, Sprache(n): de | iqb_copyright |
| Unverträgliche Aufgaben | Text |Einzeilig, Sprache(n): de | iqb_compatibility |

: {tbl-colwidths="[15,15,55,15]"}

# IQB Mathematik Primar - Item

ID of profile: `https://raw.githubusercontent.com/iqb-vocabs/p11/master/item.json`

| Name/Label | Typ | Parameter | ID Profil-Eintrag |
| :--- | :---: | :--- | :---: |
| Itemformat | [Vokabular](https://w3id.org/iqb/v27/mp/) | url: 'https://w3id.org/iqb/v27/mp/', Einmalauswahl, Nummerierung unterdrückt | s3 |
| Anforderungsbereich | [Vokabular](https://w3id.org/iqb/v10/a1/) | url: 'https://w3id.org/iqb/v10/a1/', Einmalauswahl, Nummerierung unterdrückt | s4 |
| Inhaltsbezogener Bildungsstandard primär | [Vokabular](https://w3id.org/iqb/v10/i1/) | url: 'https://w3id.org/iqb/v10/i1/', Einmalauswahl | s7 |
| Inhaltsbezogener Bildungsstandard sekundär | [Vokabular](https://w3id.org/iqb/v10/i1/) | url: 'https://w3id.org/iqb/v10/i1/', Mehrfachauswahl | s8 |
| Prozessbezogener Bildungsstandard primär | [Vokabular](https://w3id.org/iqb/v10/p1/) | url: 'https://w3id.org/iqb/v10/p1/', Einmalauswahl | s5 |
| Prozessbezogener Bildungsstandard sekundär | [Vokabular](https://w3id.org/iqb/v10/p1/) | url: 'https://w3id.org/iqb/v10/p1/', Mehrfachauswahl | s6 |
| Itemzeit | Zahl |Kommastellen: 0, Mindestwert: 0, Maximalwert: kein, als Sekunden | iqb_time_item |
| Geschätzte Schwierigkeit | [Vokabular](https://w3id.org/iqb/v26/ea/) | url: 'https://w3id.org/iqb/v26/ea/', Einmalauswahl | e4 |
| Technische Besonderheiten der Antwortoptionen | [Vokabular](https://w3id.org/iqb/v27/ti/) | url: 'https://w3id.org/iqb/v27/ti/', Mehrfachauswahl | iqb_itemtech |

: {tbl-colwidths="[15,15,55,15]"}

